# SPDX-License-Identifier: BSD-3-Clause-Clear
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.

[sku]
name=NONSAFE_IVI
slice_count=3
pvm_total_num_cpus=8

[slice0]
name=pvm.slice
post_boot_cpu_start=0
total_cpu_num=2
allow_cross_cluster=0

[slice1]
name=gvm.slice
post_boot_cpu_start=2
total_cpu_num=1
allow_cross_cluster=0

[slice2]
name=system.slice
post_boot_cpu_start=2
total_cpu_num=1
allow_cross_cluster=0
