# SPDX-License-Identifier: BSD-3-Clause-Clear
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.

[sku]
name=ADAS
slice_count=1

[slice0]
name=pvm.slice
boot_cpu_start=0
boot_cpu_end=17
post_boot_cpu_start=0
post_boot_cpu_end=17
