# SPDX-License-Identifier: BSD-3-Clause-Clear
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.

[sku]
name=ADAS
slice_count=2
pvm_total_num_cpus=18

[slice0]
name=pvm.slice
post_boot_cpu_start=0
total_cpu_num=18
allow_cross_cluster=1

[slice1]
name=rt.slice
post_boot_cpu_start=0
total_cpu_num=18
allow_cross_cluster=1
