# SPDX-License-Identifier: BSD-3-Clause-Clear
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.

[sku]
name=NONSAFE_IVI
slice_count=4
pvm_total_num_cpus=6

[slice0]
name=pvm.slice
post_boot_cpu_start=14
total_cpu_num=4
allow_cross_cluster=0

[slice1]
name=gvm.slice
post_boot_cpu_start=12
total_cpu_num=2
allow_cross_cluster=0

[slice2]
name=system.slice
post_boot_cpu_start=12
total_cpu_num=2
allow_cross_cluster=0

[slice3]
name=rt.slice
post_boot_cpu_start=12
total_cpu_num=6
allow_cross_cluster=1
