# SPDX-License-Identifier: BSD-3-Clause-Clear
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.

[sku]
name=NONSAFE_IVI
slice_count=4

[slice0]
name=pvm.slice
boot_cpu_start=6
boot_cpu_end=17
post_boot_cpu_start=12
post_boot_cpu_end=17

[slice1]
name=gvm.slice
boot_cpu_start=0
boot_cpu_end=5
post_boot_cpu_start=6
post_boot_cpu_end=11

[slice2]
name=system.slice
boot_cpu_start=0
boot_cpu_end=5
post_boot_cpu_start=6
post_boot_cpu_end=11

[slice3]
name=rt.slice
boot_cpu_start=6
boot_cpu_end=17
post_boot_cpu_start=6
post_boot_cpu_end=17
