# SPDX-License-Identifier: BSD-3-Clause-Clear
# Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.

[Coredump]
Storage=external    # store cores in /var/lib/systemd/coredump/
Compress=yes        # compress cores
ProcessSizeMax=5G   # maximum size of a core to be processed
ExternalSizeMax=2G  # maximum size of a compressed coredump to be stored on disk
MaxUse=5G           # maximum total size of all coredumps
KeepFree=20%        # keep at least 20% of disk space free
