# Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

[Service]
ExecStart=
ExecStart=/usr/sbin/irqbalance -t 5 -l /usr/bin/set_irq_bal_level.sh -f
