# SPDX-License-Identifier: GPL-2.0

ARCH?=arm64
LRH_ARCH?=aarch64

TECHPACK_BINDING_DIR=$(PWD)
TECHPACK_DTSTREE=$(TECHPACK_BINDING_DIR)

KDIR ?= $(shell echo $(PWD)/centos-stream-9)

BASE_DTB_IN ?= $(KDIR)/arch/arm64/boot/dts/qcom
DTB_MERGE_OUT ?= $(KDIR)/arch/arm64/boot/dts/qcom

#Include the paths for DT binding header files. First two are standard paths
# found in mainline kernel. Post that, add any paths for module specific, out
# of tree definition of the device tree bindings. Here, last two paths contain
# the out of tree device tree bindings.
TECHPACK_INCLUDE := $(KDIR)/scripts/dtc/include-prefixes
TECHPACK_INCLUDE += $(KDIR)/include
TECHPACK_INCLUDE += $(KDIR)/arch/$(ARCH)/boot/dts/qcom
TECHPACK_INCLUDE += $(TECHPACK_BINDING_DIR)
TECHPACK_INCLUDE += $(TECHPACK_BINDING_DIR)/oot-dt-bindings
TECHPACK_INCLUDE += $(TECHPACK_BINDING_DIR)/sa7255p-ride

SUB_TECH_BUILD:=$(wildcard techpacks/*/build.sh)

all: fail-if-no-kdir dtbos merge_dtbs.sh
	./merge_dtbs.sh $(KDIR) oot $(DTB_MERGE_OUT)

fail-if-no-kdir:
	@if [ ! -d ${KDIR} ]; then echo "Unable to find ${KDIR}, exiting!"; exit 1; fi

defconfig:
	$(MAKE) -C $(KDIR) ARCH=$(ARCH) dist-configs
	cp $(KDIR)/redhat/configs/kernel-automotive-5.14.0-$(LRH_ARCH).config \
				$(KDIR)/arch/$(ARCH)/configs/defconfig
	$(MAKE) -C $(KDIR) ARCH=$(ARCH) defconfig

dtbs : defconfig
	$(MAKE) -C $(KDIR) ARCH=$(ARCH) DTC_FLAGS="-@" dtbs

dtbos: dtbs
	$(MAKE) -C $(KDIR) ARCH=$(ARCH) dtstree=$(TECHPACK_DTSTREE) \
		DTC_INCLUDE="$(TECHPACK_INCLUDE)" DTC_FLAGS="-@" dtbs
	rm -rf oot
	mkdir oot
	cp *.dtbo oot
	@for sub_build in $(SUB_TECH_BUILD); do ./"$${sub_build}"; done

.PHONY: clean
clean:
	find  \( -name ".*.cmd" -o -name ".*.tmp" -o -name "*.dtb"  -o -name "*.dtbo" \) -delete
	rm -rf oot
