# SPDX-License-Identifier: GPL-2.0
dtb-y += sa8775p_overlay.dtbo
dtb-y += qvp/lemans_qvp.dtb
dtb-y += sa8770p-ride/sa8770p-ride.dtb
dtb-y += sa8775p-ride-mx/sa8775p-ride-mx.dtb
dtb-y += sa8650p-ride/sa8650p-ride.dtb

#include common target file
include $(PWD)/Makefile.common
