project(plat-config-generator)

set(PLAT_CONFIG_INC_PATH include)
cmake_minimum_required(VERSION 3.10)
find_package(PkgConfig)
pkg_search_module(SYSTEMD REQUIRED "systemd")
pkg_check_modules(LIBSYSTEMD REQUIRED "libsystemd")
pkg_get_variable(SYSTEMD_SYSTEM_UNIT_DIR systemd "systemdsystemunitdir")
pkg_get_variable(SYSTEMD_SYSTEM_GENERATOR_DIR systemd systemdsystemgeneratordir)
pkg_search_module(GLIB_2 REQUIRED "glib-2.0")

include_directories(${PLAT_CONFIG_INC_PATH})
link_directories(${SYSROOT_LIBDIR})
add_library(platcfg_cm SHARED common_defs.c)
target_include_directories(platcfg_cm PRIVATE ${GLIB_2_INCLUDE_DIRS})
target_link_libraries(platcfg_cm PRIVATE ${GLIB_2_LIBRARIES} minIni)
if (DEFINED IS_GEN5)
    target_compile_definitions(platcfg_cm PRIVATE IS_GEN5=1)
    target_link_libraries(platcfg_cm PRIVATE softsku)
else()
    target_compile_definitions(platcfg_cm PRIVATE IS_GEN5=0)
endif()

install(TARGETS platcfg_cm  ARCHIVE DESTINATION lib   LIBRARY DESTINATION lib    COMPONENT library)

add_executable(plat-config-generator plat-config-generator.c)
target_link_libraries(plat-config-generator PRIVATE ${LIBSYSTEMD_LDFLAGS})
target_link_libraries(plat-config-generator PRIVATE platcfg_cm)
target_compile_options(plat-config-generator PRIVATE ${LIBSYSTEMD_CFLAGS})
install(TARGETS plat-config-generator  DESTINATION ${SYSTEMD_SYSTEM_GENERATOR_DIR})

add_executable(offline-target-cpus offline-target-cpus.c)
target_link_libraries(offline-target-cpus PRIVATE ${LIBSYSTEMD_LDFLAGS})
target_link_libraries(offline-target-cpus PRIVATE platcfg_cm)
target_compile_options(offline-target-cpus PRIVATE ${LIBSYSTEMD_CFLAGS})
install(TARGETS offline-target-cpus RUNTIME DESTINATION bin COMPONENT runtime)

add_executable(reconfig-cgrp-slices reconfig-cgrp-slices.c)
target_link_libraries(reconfig-cgrp-slices PRIVATE ${LIBSYSTEMD_LDFLAGS})
target_link_libraries(reconfig-cgrp-slices PRIVATE platcfg_cm)
target_compile_options(reconfig-cgrp-slices PRIVATE ${LIBSYSTEMD_CFLAGS})
install(TARGETS reconfig-cgrp-slices RUNTIME DESTINATION bin COMPONENT runtime)

install(DIRECTORY include/  DESTINATION include)
