# SPDX-License-Identifier: BSD-3-Clause-Clear
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.

[sku]
name=FLEX
slice_count=3

[slice0]
name=pvm.slice
boot_cpu_start=12
boot_cpu_end=17
post_boot_cpu_start=14
post_boot_cpu_end=17

[slice1]
name=gvm.slice
boot_cpu_start=0
boot_cpu_end=11
post_boot_cpu_start=12
post_boot_cpu_end=13

[slice2]
name=system.slice
boot_cpu_start=0
boot_cpu_end=11
post_boot_cpu_start=12
post_boot_cpu_end=13
